services:
  - type: web
    name: dashboard
    runtime: python
    buildCommand: pip install dash pandas plotly numpy scikit-learn scipy
    startCommand: python dashboard/app.py
    envVars:
      - key: PYTHON_VERSION
        value: python-3.11.8
